### ISSUE TITLE
Liquibase could not start correctly, your database is NOT ready: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL)

### ISSUE THREAD

**Issue by pavankjadda** [pavankjadda/ApacheIgnite-JHipster-Docker#1]
```
2018-02-20 12:11:44.671 ERROR 4417 --- [ster-Executor-1] c.m.m.c.liquibase.AsyncSpringLiquibase   : Liquibase could not start correctly, your database is NOT ready: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-192]

liquibase.exception.DatabaseException: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-192]
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:363)
	at liquibase.database.AbstractJdbcDatabase.close(AbstractJdbcDatabase.java:1176)
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:400)
	at com.mycompany.myapp.config.liquibase.AsyncSpringLiquibase.initDb(AsyncSpringLiquibase.java:67)
	at com.mycompany.myapp.config.liquibase.AsyncSpringLiquibase.lambda$0(AsyncSpringLiquibase.java:50)
	at com.mycompany.myapp.async.ExceptionHandlingAsyncTaskExecutor.lambda$1(ExceptionHandlingAsyncTaskExecutor.java:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-192]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1482)
	at org.h2.jdbc.JdbcConnection.checkClosed(JdbcConnection.java:1457)
	at org.h2.jdbc.JdbcConnection.setAutoCommit(JdbcConnection.java:441)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:378)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at liquibase.database.jvm.JdbcConnection.setAutoCommit(JdbcConnection.java:361)
	... 8 common frames omitted
```

**Comment by pavankjadda** [comment]
Convert the application to `docker-compose` format i.e create docker-compose folder and start the application with `docker-compose up` command. Do not start the stand-alone database.
