### ISSUE TITLE
Invalid code lengths set projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:127)

### ISSUE THREAD

**Issue by pavankjadda** [pavankjadda/ApacheIgnite-JHipster-Docker#2]
Caused by: liquibase.exception.UnexpectedLiquibaseException: java.util.zip.ZipException: invalid code lengths set projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:127)

```
projects-app_1       | SEVERE 2/23/18 4:00 PM: liquibase: Cannot build ServiceLocator
projects-app_1       | liquibase.exception.UnexpectedLiquibaseException: java.util.zip.ZipException: invalid code lengths set
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:127)
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.<init>(ServiceLocator.java:61)
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.<clinit>(ServiceLocator.java:44)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener$LiquibasePresent.replaceServiceLocator(LiquibaseServiceLocatorApplicationListener.java:54)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener.onApplicationEvent(LiquibaseServiceLocatorApplicationListener.java:44)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener.onApplicationEvent(LiquibaseServiceLocatorApplicationListener.java:35)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
projects-app_1       | 	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
projects-app_1       | 	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
projects-app_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:292)
projects-app_1       | 	at com.projects.ProjectsApp.main(ProjectsApp.java:68)
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
projects-app_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
projects-app_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
projects-app_1       | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
projects-app_1       | 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
projects-app_1       | Caused by: java.util.zip.ZipException: invalid code lengths set
projects-app_1       | 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
projects-app_1       | 	at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.fill(Manifest.java:441)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:375)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:409)
projects-app_1       | 	at java.util.jar.Attributes.read(Attributes.java:376)
projects-app_1       | 	at java.util.jar.Manifest.read(Manifest.java:199)
projects-app_1       | 	at java.util.jar.Manifest.<init>(Manifest.java:69)
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:116)
projects-app_1       | 	... 21 more
projects-app_1       | Exception in thread "main" java.lang.reflect.InvocationTargetException
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
projects-app_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
projects-app_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
projects-app_1       | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
projects-app_1       | 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
projects-app_1       | Caused by: liquibase.exception.UnexpectedLiquibaseException: java.util.zip.ZipException: invalid code lengths set
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:127)
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.<init>(ServiceLocator.java:71)
projects-app_1       | 	at liquibase.servicelocator.CustomResolverServiceLocator.<init>(CustomResolverServiceLocator.java:16)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener$LiquibasePresent.replaceServiceLocator(LiquibaseServiceLocatorApplicationListener.java:55)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener.onApplicationEvent(LiquibaseServiceLocatorApplicationListener.java:44)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener.onApplicationEvent(LiquibaseServiceLocatorApplicationListener.java:35)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
projects-app_1       | 	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
projects-app_1       | 	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
projects-app_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:292)
projects-app_1       | 	at com.projects.ProjectsApp.main(ProjectsApp.java:68)
projects-app_1       | 	... 8 more
projects-app_1       | Caused by: java.util.zip.ZipException: invalid code lengths set
projects-app_1       | 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
projects-app_1       | 	at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.fill(Manifest.java:441)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:375)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:409)
projects-app_1       | 	at java.util.jar.Attributes.read(Attributes.java:376)
projects-app_1       | 	at java.util.jar.Manifest.read(Manifest.java:199)
projects-app_1       | 	at java.util.jar.Manifest.<init>(Manifest.java:69)
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:116)
```

**Comment by pavankjadda** [comment]
Remove folder `.m2` in home directory and compile the projects again
