### ISSUE TITLE
Method org/apache/ignite/cache/hibernate/HibernateRegionFactory.start(Lorg/hibernate/boot/spi/SessionFactoryOptions;Ljava/util/Properties;) . V is abstract

### ISSUE THREAD

**Issue by pavankjadda** [pavankjadda/ApacheIgnite-JHipster-Docker#4]
Error message when hibernate dependencies included

Error message

`
Caused by: java.lang.AbstractMethodError: Method org/apache/ignite/cache/hibernate/HibernateRegionFactory.start(Lorg/hibernate/boot/spi/SessionFactoryOptions;Ljava/util/Properties;)V is abstract` 

```
Invocation of destroy method failed on bean with name 'scopedTarget.eurekaClient': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
projects-app_1       | 2018-02-26 16:20:22.171 ERROR 8 --- [           main] o.s.boot.SpringApplication               : Application startup failed
projects-app_1       | 
projects-app_1       | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.AbstractMethodError: Method org/apache/ignite/cache/hibernate/HibernateRegionFactory.start(Lorg/hibernate/boot/spi/SessionFactoryOptions;Ljava/util/Properties;)V is abstract
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
projects-app_1       | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
projects-app_1       | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1080)
projects-app_1       | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
projects-app_1       | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
projects-app_1       | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
projects-app_1       | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
projects-app_1       | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
projects-app_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
projects-app_1       | 	at com.projects.ProjectsApp.main(ProjectsApp.java:68)
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
projects-app_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
projects-app_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
projects-app_1       | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
projects-app_1       | 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
projects-app_1       | Caused by: java.lang.AbstractMethodError: Method org/apache/ignite/cache/hibernate/HibernateRegionFactory.start(Lorg/hibernate/boot/spi/SessionFactoryOptions;Ljava/util/Properties;)V is abstract
projects-app_1       | 	at org.apache.ignite.cache.hibernate.HibernateRegionFactory.start(HibernateRegionFactory.java)
projects-app_1       | 	at org.hibernate.cache.spi.RegionFactory.start(RegionFactory.java:63)
projects-app_1       | 	at org.hibernate.internal.CacheImpl.<init>(CacheImpl.java:71)
projects-app_1       | 	at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:28)
projects-app_1       | 	at org.hibernate.engine.spi.CacheInitiator.initiateService(CacheInitiator.java:20)
projects-app_1       | 	at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.initiateService(SessionFactoryServiceRegistryImpl.java:59)
projects-app_1       | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:259)
projects-app_1       | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:233)
projects-app_1       | 	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:210)
projects-app_1       | 	at org.hibernate.service.internal.SessionFactoryServiceRegistryImpl.getService(SessionFactoryServiceRegistryImpl.java:80)
projects-app_1       | 	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:244)
projects-app_1       | 	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:452)
projects-app_1       | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:889)
projects-app_1       | 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
projects-app_1       | 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:360)
projects-app_1       | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:382)
projects-app_1       | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:371)
projects-app_1       | 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:336)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
projects-app_1       | 	... 22 common frames omitted
projects-app_1       | 

```

**Comment by pavankjadda** [comment]
In HibernateRegionFactory class method start uses Settings class from  `org.hibernate.cfg.Settings` which deprecated and HibernateRegionFactory expects class of type `org.hibernate.boot.spi.SessionFactoryOptions`. Since type is mismatched complier looking for overrided method with  org.hibernate.boot.spi.SessionFactoryOptions as parameter.

@Override public void start(Settings settings, Properties props) throws CacheException {
        String gridCfg = props.getProperty(GRID_CONFIG_PROPERTY);
        String gridName = props.getProperty(GRID_NAME_PROPERTY);

        if (gridCfg != null) {
            try {
                ignite = G.start(gridCfg);
            }
            catch (IgniteException e) {
                throw new CacheException(e);
            }
        }

**Comment by pavankjadda** [comment]
start method in SessionFactoryOptions class deprecated from hibernate 5.2+. This may be the issue.

**Comment by pavankjadda** [comment]
Refer this [discussion]( https://stackoverflow.com/questions/48993735/apache-ignite-method-hibernateregionfactory-start-v-is-abstract)

**Comment by pavankjadda** [comment]
Changing hibernate dependencies to 5.1.5 produces following error
`Caused by: liquibase.exception.UnexpectedLiquibaseException: java.util.zip.ZipException: invalid block type`


Error Message:
```
projects-app_1       | The application will start in 30s...
projects-app_1       | SEVERE 2/27/18 4:59 PM: liquibase: Cannot build ServiceLocator
projects-app_1       | liquibase.exception.UnexpectedLiquibaseException: java.util.zip.ZipException: invalid block type
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:127)
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.<init>(ServiceLocator.java:61)
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.<clinit>(ServiceLocator.java:44)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener$LiquibasePresent.replaceServiceLocator(LiquibaseServiceLocatorApplicationListener.java:54)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener.onApplicationEvent(LiquibaseServiceLocatorApplicationListener.java:44)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener.onApplicationEvent(LiquibaseServiceLocatorApplicationListener.java:35)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
projects-app_1       | 	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
projects-app_1       | 	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
projects-app_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:292)
projects-app_1       | 	at com.projects.ProjectsApp.main(ProjectsApp.java:68)
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
projects-app_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
projects-app_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
projects-app_1       | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
projects-app_1       | 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
projects-app_1       | Caused by: java.util.zip.ZipException: invalid block type
projects-app_1       | 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
projects-app_1       | 	at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.fill(Manifest.java:441)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:375)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:409)
projects-app_1       | 	at java.util.jar.Attributes.read(Attributes.java:376)
projects-app_1       | 	at java.util.jar.Manifest.read(Manifest.java:199)
projects-app_1       | 	at java.util.jar.Manifest.<init>(Manifest.java:69)
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:116)
projects-app_1       | 	... 21 more
projects-app_1       | Exception in thread "main" java.lang.reflect.InvocationTargetException
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
projects-app_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
projects-app_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
projects-app_1       | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
projects-app_1       | 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
projects-app_1       | Caused by: liquibase.exception.UnexpectedLiquibaseException: java.util.zip.ZipException: invalid block type
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:127)
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.<init>(ServiceLocator.java:71)
projects-app_1       | 	at liquibase.servicelocator.CustomResolverServiceLocator.<init>(CustomResolverServiceLocator.java:16)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener$LiquibasePresent.replaceServiceLocator(LiquibaseServiceLocatorApplicationListener.java:55)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener.onApplicationEvent(LiquibaseServiceLocatorApplicationListener.java:44)
projects-app_1       | 	at org.springframework.boot.liquibase.LiquibaseServiceLocatorApplicationListener.onApplicationEvent(LiquibaseServiceLocatorApplicationListener.java:35)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
projects-app_1       | 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:122)
projects-app_1       | 	at org.springframework.boot.context.event.EventPublishingRunListener.starting(EventPublishingRunListener.java:69)
projects-app_1       | 	at org.springframework.boot.SpringApplicationRunListeners.starting(SpringApplicationRunListeners.java:48)
projects-app_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:292)
projects-app_1       | 	at com.projects.ProjectsApp.main(ProjectsApp.java:68)
projects-app_1       | 	... 8 more
projects-app_1       | Caused by: java.util.zip.ZipException: invalid block type
projects-app_1       | 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
projects-app_1       | 	at org.springframework.boot.loader.jar.ZipInflaterInputStream.read(ZipInflaterInputStream.java:52)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.fill(Manifest.java:441)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:375)
projects-app_1       | 	at java.util.jar.Manifest$FastInputStream.readLine(Manifest.java:409)
projects-app_1       | 	at java.util.jar.Attributes.read(Attributes.java:376)
projects-app_1       | 	at java.util.jar.Manifest.read(Manifest.java:199)
projects-app_1       | 	at java.util.jar.Manifest.<init>(Manifest.java:69)
projects-app_1       | 	at liquibase.servicelocator.ServiceLocator.setResourceAccessor(ServiceLocator.java:116)
```

**Comment by pavankjadda** [comment]
New Error message starts popping up

`**org.hibernate.boot.spi.SessionFactoryBuilderImplementor.markAsJpaBootstrap()V**`

```
Invocation of destroy method failed on bean with name 'scopedTarget.eurekaClient': org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'eurekaInstanceConfigBean': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
projects-app_1       | 2018-03-01 16:59:57.967 ERROR 7 --- [           main] o.s.boot.SpringApplication               : Application startup failed
projects-app_1       | 
projects-app_1       | org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoSuchMethodError: org.hibernate.boot.spi.SessionFactoryBuilderImplementor.markAsJpaBootstrap()V
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
projects-app_1       | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
projects-app_1       | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1080)
projects-app_1       | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857)
projects-app_1       | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
projects-app_1       | 	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
projects-app_1       | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
projects-app_1       | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
projects-app_1       | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
projects-app_1       | 	at com.projects.ProjectsApp.main(ProjectsApp.java:68)
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
projects-app_1       | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
projects-app_1       | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
projects-app_1       | 	at java.lang.reflect.Method.invoke(Method.java:498)
projects-app_1       | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
projects-app_1       | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
projects-app_1       | 	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59)
projects-app_1       | Caused by: java.lang.NoSuchMethodError: org.hibernate.boot.spi.SessionFactoryBuilderImplementor.markAsJpaBootstrap()V
projects-app_1       | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.populate(EntityManagerFactoryBuilderImpl.java:897)
projects-app_1       | 	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:886)
projects-app_1       | 	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:60)
projects-app_1       | 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:360)
projects-app_1       | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:382)
projects-app_1       | 	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:371)
projects-app_1       | 	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:336)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687)
projects-app_1       | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624)
```

**Comment by pavankjadda** [comment]
Changed hibernate.version to 5.1.10 and removed default hibernate dependencies and added following dependencies.

```
     <dependency>
           <groupId>org.hibernate</groupId>
           <artifactId>hibernate-core</artifactId>
           <version>${hibernate.version}</version>
       </dependency>
       
     <dependency>
           <groupId>org.hibernate</groupId>
           <artifactId>hibernate-envers</artifactId>
           <version>${hibernate.version}</version>
       </dependency>
```
       
This change produces following error. 
`Unable to resolve name org.apache.ignite.cache.hibernate.HibernateRegionFactory as strategy org.hibernate.cache.spi.RegionFactory`

Please track the new issue [here](https://github.com/pavankjadda/ApacheIgnite-JHipster-Docker/issues/5)
